name: Build and push Docker

on:
  push: 
    branches: ['**']
    tags: ['**']

jobs:
  docker-build-push:
    uses: AlejoAsd/actions/.github/workflows/docker-build-push-github.yaml@feature/docker-build-push
    with:
      docker-build-context: 'test/'
      docker-filepath: 'My-Custom-Dockerfile'
